production: true
permalink: pretty
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from
exclude:
  - vendor
  - README.md
  - Makefile
  - Gemfile
  - Gemfile.lock
  - CHANGELOG.md
  - .travis.yml
