title: Threephase
tagline: Christopher Peplin
description: Christopher Peplin's personal and professional site.
url: https://threephase.xyz
permalink: pretty
author: Christopher Peplin
plugins:
    - jekyll-sitemap
    - jekyll-redirect-from
    - jekyll-seo-tag
exclude:
  - vendor
  - LICENSE.md
  - THEME_LICENSE.md
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /:slug
  projects:
    output: true
    permalink: /project/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed
