header_settings:
  logo_image:
  logo_width: 300

menu_settings:
  menu_items:
    - title: 'About'
      url: '/about/'

grid_settings:
  overlay_opacity: 0.8
  grid_spacing: 20

social_settings:
  linkedin_url: 'https://www.linkedin.com/in/peplin/'
  github_url: 'http://github.com/peplin'
  flickr_url: 'https://www.flickr.com/photos/christopherpeplin/'
  bandcamp_url: 'https://bandcamp.com/peplin'

color_settings:
  background_color: '#FFFFFF'
  background_alt_color: '#F9F9FB'
  text_dark_color: '#2A2F36'
  text_medium_color: '#2A2F36'
  text_light_color: '#ABB7B7'
  accent_color: '#0C5DF2'
  border_color: '#dddddd'
  overlay_background_color: '#0C5DF2'
  overlay_text_color: '#ffffff'
  overlay_accent_color: '#2A2F36'
  error_color: '#D64541'

font_settings:
  title_font: '"Montserrat", sans-serif'
  body_font: '"Montserrat", sans-serif'
  regular_weight: 300
  bold_weight: 500
  site_title:
    small_size: 25
    medium_size: 35
    large_size: 38
    weight: 500
    letter_spacing: -0.02
  site_tagline:
    small_size: 16
    medium_size: 14
    large_size: 16
    weight: 300
    letter_spacing: 0
    line_height: 1.5
  menu:
    small_size: 30
    medium_size: 15
    large_size: 16
    weight: 500
    letter_spacing: 0
  grid_item_title:
    small_size: 22
    medium_size: 26
    large_size: 30
    weight: 500
    letter_spacing: -0.02
  grid_item_subtitle:
    small_size: 15
    medium_size: 16
    large_size: 17
    weight: 300
    letter_spacing: 0
  h1:
    small_size: 25
    medium_size: 35
    large_size: 42
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h2:
    small_size: 22
    medium_size: 30
    large_size: 32
    weight: 500
    letter_spacing: -0.02
    line_height: 1.2
  h3:
    small_size: 22
    medium_size: 25
    large_size: 30
    weight: 500
    letter_spacing: -0.02
    line_height: 1.3
  h4:
    small_size: 17
    medium_size: 22
    large_size: 22
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h5:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  h6:
    small_size: 17
    medium_size: 20
    large_size: 20
    weight: 500
    letter_spacing: 0
    line_height: 1.6
  p:
    small_size: 16
    medium_size: 18
    large_size: 18
    weight: 300
    letter_spacing: 0
    line_height: 1.6
  blockquote:
    small_size: 18
    medium_size: 20
    large_size: 24
    weight: 300
    letter_spacing: -0.02
    line_height: 1.6
  buttons:
    weight: 500
    letter_spacing: 0
